adding retry checking on workflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -50,8 +50,13 @@ jobs:
 
       - name: Health Check App
         run: |
-          echo "🔍 Checking app at http://${{ steps.ec2_ip.outputs.public_ip }}"
-          curl -f http://${{ steps.ec2_ip.outputs.public_ip }} || (echo "App not responding" && exit 1)
+          for i in {1..10}; do
+            echo "🔍 Checking app at http://${{ steps.ec2_ip.outputs.public_ip }}"
+            curl -f http://${{ steps.ec2_ip.outputs.public_ip }} || (echo "App not responding" && exit 1)
+            echo "Attempt $i failed. Retrying in 5 seconds..."
+            sleep 5
+          done
+          exit 1
 
       - name: Keep App Running
         run: |
